name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # or match your project version

      - name: Publish .NET app
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'self-hosted-runner-test-web-app'
          package: ./publish
